# Generated by Django 5.1.7 on 2025-03-30 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_inventory_stock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
