# Generated by Django 5.1.7 on 2025-03-30 09:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_waste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
