# Generated by Django 5.1.7 on 2025-03-31 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_inventory_date_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('date', models.DateField()),
                ('item_name', models.CharField(max_length=200)),
                ('item_type', models.CharField(max_length=100)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(max_length=50)),
                ('received_by', models.CharField(max_length=100)),
                ('time_of_sale', models.CharField(max_length=50)),
                ('ingredients', models.TextField()),
            ],
        ),
    ]
